# Generated by Django 5.1.4 on 2024-12-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='start_time',
            new_name='start',
        ),
    ]
