# Generated by Django 5.1.4 on 2024-12-20 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='producer',
            field=models.ForeignKey(default=2, limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='produced_audio_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='artist',
            field=models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
