# Generated by Django 5.1.4 on 2024-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_audiofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
