# Generated by Django 5.1.4 on 2025-02-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_audiofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
